#!/bin/sh
#
# wmrc display variables
# (c) ix 2016
#

# these are seperate from the rest of the
# global variables as they have to run dattr
# and pfd, which can be rather slow during
# some tasks

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}

. $XDG_CONFIG_HOME/wmrc/config
. $XDG_CONFIG_HOME/wmrc/globals

CURDISP=$(pfd)
SW=$(dattr -w $CURDISP &)
BSH=$(dattr -h $CURDISP &)
SX=$(dattr -x $CURDISP &)
SY=$(dattr -y $CURDISP &)
SH=$((BSH - PANEL))
HSW=$((SW/2 - 2*BWIDTH - GAP - GAP/2))
HSH=$((SH/2 - 2*BWIDTH - GAP - GAP/2))
