#!/bin/sh
#
# wmrc display variables
# (c) ix 2016
#

# these are seperate from the rest of the
# global variables as they have to run dattr
# and pfd, which can be rather slow during
# some tasks

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}

. $XDG_CONFIG_HOME/wmrc/config

# variables for window positioning with panels but ignoring gaps
CURDISP=$(pfd)
SW=$(dattr -w $CURDISP &)
BSH=$(dattr -h $CURDISP &)
SX=$(dattr -x $CURDISP &)
SY=$(dattr -y $CURDISP &)
SH=$((BSH - PANEL))

# variables for window positioning with outer gaps and panels
# (borders are not substracted here!)
LEFT=$((SX + GAP))
TOP=$((SY + GAP + PANEL))
WHOLEW=$((SW - 2*GAP))
WHOLEH=$((SH - 2*GAP))
