#!/bin/sh
#
# evhandle - perform actions when window status changes
# (c) ix 2016
#

while IFS=': ' read ev wid; do
  case $1 in
    -d) echo "$ev" "$wid"
  esac
  case $ev in
    CREATE) #$(<~/var/wm/$wid/ignored) || winopen $wid ;;
      wattr o $wid || winopen $wid ;;

    MAP) #$(<~/var/wm/$wid/ignored) || focuswrap $wid ;;
      wattr o $wid || focuswrap $wid ;;

    DESTROY) [ -e ~/var/wm/$(<~/var/wm/focused) ] || focuswrap prev 2>/dev/null ;;

    ENTER) #$(<~/var/wm/$wid/ignored) || focuswrap $wid ;;
      wattr o $wid || focuswrap $wid ;;
  esac
done
