#!/bin/sh
#
# expandw - expand window horizontally/vertically
# (c) ix 2016
#

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

. $XDG_CONFIG_HOME/wmrc/config
. $XDG_CONFIG_HOME/wmrc/globals
. $XDG_CONFIG_HOME/wmrc/disp

[ -d $EXPANDDIR ] || mkdir -p $EXPANDDIR

while getopts hv opt; do
  case $opt in
    h) DIRECTION=horiz ;;
    v) DIRECTION=vert ;;
  esac
done

shift $((OPTIND - 1))

MONITOR=$(pfd)

usage() {
  echo "usage: $(basename $0) [-hv] <wid>" >&2
  exit ${1:-0}
}

[ -z $1 ] && usage

expand() {
  wattr xywhi $CUR > $EXPANDDIR/$CUR
  case $DIRECTION in
    vert) GEO=$(printf '%d 0 %d %d' $(wattr xw $CUR) $((BSH - 2*BWIDTH))) ;;
    horiz) GEO=$(printf "$SX %d %d %d" $(wattr y $CUR) $((SW - 2*BWIDTH)) $(wattr h $CUR)) ;;
  esac
  wtp $GEO $CUR
}

collapse() {
  [ -f $EXPANDDIR/$CUR ] || return
  wtp $(grep $CUR $EXPANDDIR/$CUR)
  rm $EXPANDDIR/$CUR
}

checkmax() {
  case $DIRECTION in
    vert) [ $(wattr h $CUR) -eq $((BSH - 2*BWIDTH)) ] && return 0 ;;
    horiz) [ $(wattr w $CUR) -eq $((SW - 2*BWIDTH)) ] && return 0 ;;
  esac
}

checkmax && collapse || expand
