#!/bin/sh
#
# wmrc globals - global variables/funcs for wmrc
# (c) ix 2016
#

seq() {
    local count end

    if [ -n "$2" ]; then
        count="$1"
        end="$2"
    elif [ -n "$1" ]; then
        count=0
        end="$1"
    fi

    while [ "$count" -le "$end" ]; do
        echo "$count"
        count=$(($count+1))
    done
}

CUR=$(pfw)
WW=$(wattr w $CUR)
WH=$(wattr h $CUR)
ROOT=$(lsw -r)
BWIDTH=$(wattr b $CUR)
