#!/bin/sh
#
# wmrc globals - global variables/funcs for wmrc
# (c) ix 2016
#

seq() {
    if [ ! -z "$1" ]; then
        actual=$(($1 - 1))
    fi
    i=${actual:-0}
    while [ "$i" -lt $2 ]; do
        i=$(($i+1))
    done
}

CUR=$(pfw)
WW=$(wattr w $CUR)
WH=$(wattr h $CUR)
ROOT=$(lsw -r)
BWIDTH=$(wattr b $CUR)
