#!/bin/sh
#
# groupmgr - manage groups for windows
# (c) ix && kori 2016
#

## FALLBACK VARIABLES
# As this script makes changes to
# the filesystem, these are here for extra
# safety.

GRPROOT=/tmp/groups
GRPSTATROOT=/tmp/grpstat
GRPNUM=5

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

. $XDG_CONFIG_HOME/wmrc/config
. $XDG_CONFIG_HOME/wmrc/globals

if [ "$WMRC_TEMPDIR" ]; then
  GRPROOT="$WMRC_TEMPDIR"/groups
  GRPSTATROOT="$WMRC_TEMPDIR"/grpstat
fi

usage() {
  echo "$(basename $0) [-adsth <gid>]"
}

addtgrp() {
  :> "$GRPROOT"/$2/$1
  showgrp $2
}

removefgrp() {
  if [ "$2" = "all" ]; then
    for grp in "$(seq $GRPNUM)"; do
      rm -f "$GRPROOT"/*/$1
    done
  else
    rm -f "$GRPROOT"/$2/$1
  fi
}

findgrp() {
  file=$(find "$GRPROOT" -name "$1")
  [ -n "$file" ] && basename $(dirname $file)
}

showgrp() {
  for file in "$GRPROOT"/$1/*; do
    wid=$(basename $file)
    mapw -m $wid
  done
  echo 1 > "$GRPSTATROOT"/$1
}

hidegrp() {
  for file in "$GRPROOT"/$1/*; do
    wid=$(basename $file)
    mapw -u $wid
  done
  echo 0 > "$GRPSTATROOT"/$1
}

togggrp() {
  wid=$(ls -1 "$GRPROOT"/$1 | sed 1q)

  [ -z "$wid" ] && return
  wattr m $wid
  if [ $? -eq 0 ]; then
    hidegrp $1
  elif [ $? -eq 1 ]; then
    showgrp $1
  fi
}

cgrps() {
  if [ ! -d "$GRPSTATROOT" ]; then
    mkdir "$GRPSTATROOT"
  fi
  for gid in $(seq 1 $GRPNUM ); do
    [ -d "$GRPROOT"/$gid ] || mkdir -p "$GRPROOT"/$gid
  done

  for file in $(find "$GRPROOT" -type f); do
    wid=$(basename $file)
    wattr $wid || rm -f $file
  done

  for gstat in $(seq 1 $GRPNUM); do
    if [ $(find "$GRPROOT"/$gstat -maxdepth 0 -type d -empty) ]; then
      echo 0 > "$GRPSTATROOT"/$gstat
    fi
  done
}

cgrps

while getopts ":a:d:gs:t:h:" opt; do
  case $opt in
    a) addtgrp $CUR $OPTARG ;;
    d) removefgrp $CUR $OPTARG ;;
    g) findgrp $CUR ;;
    s) showgrp $OPTARG ;;
    t) togggrp $OPTARG ;;
    h) hidegrp $OPTARG ;;
    *) usage && exit 1 ;;
  esac
done

[ $# -eq 0 ] && tree --noreport "$GRPROOT"
