#!/bin/sh
#
# killwin - kill window (changes based on what window)
# (c) ix && wildefyr 2016
#

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}

. $XDG_CONFIG_HOME/wmrc/globals

WIN=${@:-$CUR}

[ "$(lsw -a | grep $WIN)" ] && echo 'window not valid'

windowc=$(winclass -c $WIN)
windowm=$(winclass -m $WIN)

if [ "$windowm" = "Firefox" ]; then
  killwa $WIN
elif [ "$windowc" = "urxvt" ]; then
  killwa $WIN
else
  killw $WIN
fi
