#!/bin/sh
#
# killw - kill window (changes based on what window)
# (c) ix && wildefyr 2016
#

wid=$(pfw)
windowc=$(winclass -c $wid)
windowm=$(winclass -m $wid)

if [ "$windowm" = "Firefox" ]; then
  killwa $wid
elif [ "$windowc" = "urxvt" ]; then
  killwa $wid
else
  killw $wid
fi
