#!/bin/sh
#
# killx - kills the X server, cleaning temp files and such
# (c) ix 2016
#

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}

. $XDG_CONFIG_HOME/wmrc/config

rm /tmp/groups/*/*
rm /tmp/grpstat/*
echo 0 > /tmp/grpstat/1
echo 0 > /tmp/grpstat/2
echo 0 > /tmp/grpstat/3
echo 0 > /tmp/grpstat/4
echo 0 > /tmp/grpstat/5
killall sxhkd
killall wew
killall xwait
