#!/bin/sh
#
# pulsew - pulse the active window border
# (c) ix 2016
#

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}

. $XDG_CONFIG_HOME/wmrc/config

while :; do
  cols=$(tac < $PULSECOLS | cat - $PULSECOLS | tr -d '#')
  for col in $cols; do
    test "`wattr wh $PFW`" != "`wattr wh $(lsw -r)`" && chwb -c $col $PFW
    sleep $FREQ
  done
done
