#!/bin/sh
#
# setborder - set border of a window
# (c) ix 2016
#

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

. $XDG_CONFIG_HOME/wmrc/config

wattr $2 || return
wattr o $2 && return

[ "$(wattr xywh $2)" = "$(wattr xywh $ROOT)" ] && return
if [ -f $FSFILE ] \
  && [ "$(cat $FSFILE | awk '{print $5}')" = "$2" ] \
  && [ "$(wattr x $(pfw))" = "$(cat $FSFILE | awk '{print $1}')" ]; then
  exit 1
fi

case $1 in
  active) chwb -s $BW -c $ACTIVE $2 ;;
  inactive) chwb -s $BW -c $INACTIVE $2 ;;
esac
