#!/bin/sh
#
# snapw - snap a window left, right, up, down
# (c) ix 2016
#

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}

. $XDG_CONFIG_HOME/wmrc/config
. $XDG_CONFIG_HOME/wmrc/globals
. $XDG_CONFIG_HOME/wmrc/disp

usage() {
  printf '%s\n' "usage: $(basename $0) <left|down|up|right> <wid>"
}

case $2 in
  0x*) CUR=$2 ;;
esac

right() {
  wtp $((SX + SW - SW/2 + GAP/2)) $((SY + GAP + PANEL)) $((SW/2 - 2*BWIDTH - GAP - GAP/2)) $((SH - 2*BWIDTH - 2*GAP)) $PFW
}

left() {
  wtp $((SX + GAP)) $((SY + GAP + PANEL)) $((SW/2 - 2*BWIDTH - GAP - GAP/2)) $((SH - 2*BWIDTH - 2*GAP)) $PFW
}

down() {
  up
  #wtp $((SX + GAP)) $((SY + SH - SH/2)) $((SW - 2*GAP - 2*BWIDTH)) $((SH/2 - 2*BWIDTH - GAP - GAP/2)) $PFW
  wmv 0 $((SH/2 - BWIDTH - GAP/2)) $PFW
}

up() {
  wtp $((SX + GAP)) $((SY + GAP + PANEL)) $((SW - 2*GAP - 2*BWIDTH)) $((SH/2 - 2*BWIDTH - GAP - GAP/2)) $PFW
}

topright() {
  wtp $((SX + SW - SW/2 + GAP/2)) $((SY + GAP + PANEL)) $HSW $HSH $PFW
}

topleft() {
  wtp $((SX + GAP)) $((SY + GAP + PANEL)) $HSW $HSH $PFW
}

bottomright() {
  wtp $((SX + SW - SW/2 + GAP/2)) $((SY + SH - SH/2 + GAP/2 + PANEL)) $HSW $HSH $PFW
}


bottomleft() {
  wtp $((SX + GAP)) $((SY + SH - SH/2 + GAP/2 + PANEL)) $HSW $HSH $PFW
}

case $1 in
  left) left ;;
  right) right ;;
  down) down ;;
  up) up ;;
  tr) topright ;;
  tl) topleft ;;
  br) bottomright ;;
  bl) bottomleft ;;
  *) usage ;;
esac
