#!/bin/sh
#
# snapw - snap a window left, right, up, down
# (c) ix & milsen 2016
#

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}

. $XDG_CONFIG_HOME/wmrc/config
. $XDG_CONFIG_HOME/wmrc/globals
. $XDG_CONFIG_HOME/wmrc/disp

usage() {
  printf '%s\n' "usage: $(basename $0) <left|down|up|right> <wid>"
}

case $2 in
  0x*) CUR=$2 ;;
esac

# define variables for screen positioning
LEFT=$((SX + GAP))
RIGHT=$((SX + SW - SW/2 + GAP/2))
TOP=$((SY + GAP + PANEL))
BOTTOM=$((PANEL + SY + SH - SH/2))

HALFW=$((SW/2 - 2*BWIDTH - GAP - GAP/2))
WHOLEW=$((SW - 2*GAP - 2*BWIDTH))
HALFH=$((SH/2 - 2*BWIDTH - GAP - GAP/2))
WHOLEH=$((SH - 2*GAP - 2*BWIDTH))

case $1 in
  left|l)          wtp $LEFT  $TOP    $HALFW  $WHOLEH $CUR ;;
  right|r)         wtp $RIGHT $TOP    $HALFW  $WHOLEH $CUR ;;
  bottom|down|d|b) wtp $LEFT  $BOTTOM $WHOLEW $HALFH  $CUR ;;
  top|up|u|t)      wtp $LEFT  $TOP    $WHOLEW $HALFH  $CUR ;;
  topright|tr)     wtp $RIGHT $TOP    $HALFW  $HALFH  $CUR ;;
  topleft|tl)      wtp $LEFT  $TOP    $HALFW  $HALFH  $CUR ;;
  bottomright|br)  wtp $RIGHT $BOTTOM $HALFW  $HALFH  $CUR ;;
  bottomleft|bl)   wtp $LEFT  $BOTTOM $HALFW  $HALFH  $CUR ;;
  middle|md|m)     wtp $LEFT  $TOP    $WHOLEW $WHOLEH $CUR ;;
  *) usage ;;
esac
