#!/bin/sh
#
# snapw - snap a window left, right, up, down
# (c) ix 2016
#

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}

. $XDG_CONFIG_HOME/wmrc/globals
. $XDG_CONFIG_HOME/wmrc/disp

usage() {
  printf '%s\n' "usage: $(basename $0) <left|down|up|right> <wid>"
}

case $2 in
  0x*) CUR=$2 ;;
esac

right() {
  wtp $((SX + SW - SW/2)) $SY $((SW/2 - 2*BWIDTH)) $((SH - 2*BWIDTH)) $PFW
}

left() {
  wtp $SX $SY $((SW/2 - 2*BWIDTH)) $((SH - 2*BWIDTH)) $PFW
}

down() {
  wtp $SX $((SY + SH - SH/2)) $((SW - 2*BWIDTH)) $((SH/2 - 2*BWIDTH)) $PFW
}

up() {
  wtp $SX $SY $((SW - 2*BWIDTH)) $((SH/2 - 2*BWIDTH)) $PFW
}

case $1 in
  left) left ;;
  right) right ;;
  down) down ;;
  up) up ;;
  *) usage ;;
esac
