#!/bin/sh
#
# wchg - perform actions when window status changes
# (c) arcetera 2015
#

while IFS=: read ev wid; do
  case $ev in
    4) 
      if ! wattr o $wid; then
        wfw $wid
      fi
      ;;

    16) 
      if ! wattr o $wid; then
        wtest $wid
        if [ $(lsw | wc -l) -eq 1 ]; then
          blrbg &
        fi
      fi
      ;;

    19)
      if ! wattr o $wid; then
        wfw $wid 
	if [ $(lsw | wc -l) -eq 1 ]; then
	  blrbg &
	fi
      fi
      ;;

    18) 
      wattr $(pfw) || wfw prev 2>/dev/null
      if [ $(lsw | wc -l) -eq 0 ]; then
        blrbg 0 &
      fi
      ;;

    7) 
      if ! wattr o $wid; then
        wfw $wid 
      fi
      ;;
  esac
done
