#!/bin/sh
#
# wtest - perform actions based on different windows
# (c) arcetera 2015 
#

usage() {
  echo "usage: $(basename $0) <wid>"
  exit 1
}

if [ -z $1 ]; then
  usage
fi

wid=$1
windowc=$(wcls c $wid)
windowm=$(wcls m $wid)

if [ $(lsw | wc -l) -eq 1 ]; then
  cw $wid
elif [ "$windowc" = "Telegram" ]; then
  cw $wid
  blrbg
else
  cw $wid
fi
